### ISSUE TITLE
Feature Request: Like PlugParser add PhoenixTemplate

### ISSUE THREAD

**Issue by chintan-mishra** [lexmag/msgpax#50]
## Description:
`PlugParser` module within the package allows us to easily deserialize MsgPack sent in a request to the server. Similarly, while sending a response as MsgPack if a Phoenix template transforms data to MsgPack then it'd be very easy to use the package within Phoenix HTTP projects.

## Implementation
[This](https://hexdocs.pm/phoenix/Phoenix.Template.html#module-format-encoders) documentation has complete details on how this can be done.
  -  Adding `encode_to_iodata/1` function in the `Msgpax` module will get this done
  -  Documentation reflecting how to use this in Phoenix projects

**Comment by chintan-mishra** [comment]
If the community and maintainers are interested then I can start a PR, as I have done this in my local Phoenix project and I can quickly do the same here as well.

**Comment by lexmag** [comment]
Thanks @chintan-mishra for starting the discussion.
I think in contrast with `PlugParser` adding a Phoenix format encoder in user's application is rather a straightforward thing. From my experience, it could also need a customized encoding by utilizing `pack/2` with options.
I'm closing the issue due to the aforementioned aspects.
